spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/postservice
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    store-type: jdbc


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  profiles:
    include: oauth

logging.level:
  org.springframework: debug
    web: debug


