spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: false
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://postservice.cm7tu0nngbsw.ap-northeast-2.rds.amazonaws.com:3306/postservice
      username: wonjuyeon
      password: juyeoun1158!
      driver-class-name: org.mariadb.jdbc.Driver