spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 89494963232-0fp01t2ulbpffddmbdc148jffcqvmppn.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: EFeeRhWARjcvj64XIywz
            client-secret: c93aL2Goap
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response